ファーストコミット
NByamane/rest-countries-api-with-color-theme-switcher-master pull request #1
Opened 2024-08-08 02:46 UTC by NByamane

国データ検索ページを作成しました。

## 課題元
https://www.frontendmentor.io/challenges/rest-countries-api-with-color-theme-switcher-5cacc469fec04111f7b848ca

## 備考

- Contextを使用して、APIデータを全ページからアクセス可能に設定しました
- メモに記載してますが、app/country/[cca3]/page.tsxでのCSS importで、@でパス指定できないのと型宣言周りのエラーが出てるのが気になってます🥲原因がわかっていません😇

2024-08-09 14:37 UTC, NBmaeda requested changes
全体的に良くできていると思います！👏
ただ細かいところでもう少しブラッシュアップできそうな点があったのでコメントさせてもらってます！

可能な限りで対応してみてください🙏

2024-08-09 14:37 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +import countryDetailStyles from "../../../css/countryDetail.module.css"; //ここ、@で指定できないのと型宣言が見つかりませんというエラーが出ますが原因がわかりません😇反映はされてます
僕は問題なく指定できる&エラー出ないですね🤔
主にルート直下のファイルの位置が変わっちゃってるor不必要なファイルが配置されちゃってうとかな気がしなくもないですが...
以下、僕のルート直下です。

<img width="239" alt="スクリーンショット 2024-08-09 19 57 26" src="https://github.com/user-attachments/assets/ce191473-1779-4169-89db-8e9379886530">

2024-08-09 14:37 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +  console.log(country.name.nativeName);
この行以降のcountryは以下のエラーが出てます。
`'country' は 'undefined' の可能性があります。ts(18048)`

以下みたいな感じで早期リターンしてあげるのも1つの手かもです💡
```
if(!country){
  return <div>データが見つかりませんでした。</div>;
}
```

2024-08-09 14:37 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +  const country = countryData.find(countryItem => countryItem.cca3 === cca3);
もし以下の行で型推測うまくいかないならですが、ここを`(countryItem: CountryData) => ...`とかにしたら良いかも？

2024-08-09 14:37 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +  const currencyNames = Object.values(country.currencies).map((countryItem) => (countryItem as { name: string; symbol: string }).name);
ここ型アサーションなくてもいけないですか？
→自分はいけました🤔

2024-08-09 14:37 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +            <p className={countryDetailStyles.countryDataItem}><span className={countryDetailStyles.countryDataItemTtl}>Native Name:</span> {nativeName}</p>
この塊をコンポーネントとして分割してあげると、見通し良くなるかもしれないですね💡
同じような`p > span`のネストが並んじゃっている気がするので。
とりあえずのfirst commitで、この後対応予定とかならこのコメントは無視してください！

2024-08-09 14:37 UTC, NBmaeda commented on src/components/CountryCard.tsx
> +import countryCardStyles from "@/css/countryCard.module.css";
多分毎回`countryCardStyles`って書くの大変だと思うので、複数の`module.css`読み込まないのであればどのファイルでも一律`styles`みたいな名前でも良いと思います💡

2024-08-09 14:37 UTC, NBmaeda commented on src/components/Header.tsx
> +  }, [isOn]);
ここなんですが、`body`要素を持っている親コンポーネントで`darkMode`のためのstateを定義して、setter関数をこのコンポーネントを渡すようにすれば`useEffect`を使わなくても良くなりそうです。

その場合、`layout.tsx`はクライアントコンポーネントにするのは良くないため(複数のページがサーバーコンポーネントの恩恵を受けられなくなる)、それ用のラッパーコンポーネントを作った方が良いと思います。

2024-08-09 14:37 UTC, NBmaeda commented on src/app/page.tsx
> +  if (loading) { return <div>Loading...</div>; }
ここがちょっと勿体無いなと思うのが、ページ表示後にfetchをしている間、inputに何も入力できない点です。
裏側でfetchしているのであれば、inputだけでも表示していれば入力している間にfetchが終わってよりユーザビリティは上がりそうです💡

入力後にfetchが終わっていなければ、そこで初めて「loading」を表示しつつfetchtが終わり次第結果を表示すると良いかなと思います。

2024-08-19 07:46 UTC, NByamane commented on src/app/country/[cca3]/page.tsx
> +import countryDetailStyles from "../../../css/countryDetail.module.css"; //ここ、@で指定できないのと型宣言が見つかりませんというエラーが出ますが原因がわかりません😇反映はされてます
@NBmaeda 
お疲れ様です！
ご確認ありがとうございます🙇‍♀️
こちら、ルート直下のファイル構成は同じだったんですが、
css.d.tsという型定義のファイルを作成したところエラーが解消されました😳
この型定義のファイルって、もともとNext.jsインストール時に作成されてるものではないんですかね…？🤔

2024-08-19 08:14 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +import countryDetailStyles from "../../../css/countryDetail.module.css"; //ここ、@で指定できないのと型宣言が見つかりませんというエラーが出ますが原因がわかりません😇反映はされてます
@NByamane 
> css.d.tsという型定義のファイルを作成したところエラーが解消されました😳
この型定義のファイルって、もともとNext.jsインストール時に作成されてるものではないんですかね…？🤔

謎...本来必要ならインストール時に作成されるのですが、されてないのを見ると別のとこで型定義してるのかなという感じです。
node_modules再インストールとかでダメなら、原因追及は時間かかりそうです🤔

2024-08-19 08:36 UTC, NByamane commented on src/app/country/[cca3]/page.tsx
> +import countryDetailStyles from "../../../css/countryDetail.module.css"; //ここ、@で指定できないのと型宣言が見つかりませんというエラーが出ますが原因がわかりません😇反映はされてます
@NBmaeda 
謎現象が起きました🥹
ただちゃんと動いてるので、一旦ステイしときます…😇

https://github.com/user-attachments/assets/eba515eb-0b24-4469-b372-0996c18db0f8

2024-08-19 09:44 UTC, NByamane commented
@NBmaeda 
お疲れ様です🙇‍♀️
レビューありがとうございました✨
修正対応を行いましたので、ご確認の程よろしくお願い致します🍧

2024-08-20 06:48 UTC, NBmaeda approved these changes
対応ありがとうございます！
概ね問題ないと思うのでApproveしました！🎉

`src/app/country/[cca3]/page.tsx`で型エラーが出ているので、そこだけどうするかを考えてほしいなという感じです。

Next.js + TypepScriptを使ってみたりcontextを使ったりと、なかなか大変だったと思いますがよくできていると思います👏
お疲れ様でした！

2024-08-20 06:48 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +            <CountryDetailItem title="Capital" value={country.capital} />
54行目もなんですが、`型 'string[]' を型 'string' に割り当てることはできません。`というエラーが出ています。
`country.capital`と`country.tld`は`string[]`型になっていると思うので、`CountryDetailItem`の`value`propsに`string`型の状態で入るようにするか、`CountryDetailItem`で`string[]`型を許容してあげるようにした方が良いと思います。

2024-08-26 01:42 UTC, NByamane commented on src/app/country/[cca3]/page.tsx
> +            <CountryDetailItem title="Capital" value={country.capital} />
@NBmaeda 
ありがとうございます🙇‍♀️
`value` propsでstring[]も許容するように設定したのですが、こちらでいかがでしょうか？🙂

2024-08-27 06:21 UTC, NBmaeda commented on src/app/country/[cca3]/page.tsx
> +            <CountryDetailItem title="Capital" value={country.capital} />
@NByamane 
対応ありがとうございます！
エラーは出なくなったのですが、`["foo", "bar"]`とかの場合`Capital: foobar`みたいな感じで表示されそうですね🤔

`string[]`の場合は`CountryDetailItem`コンポーネント内で`Array.prototype.join(', ')`してあげるか、今回の修正とは逆の話になっちゃいますが`string`のみ許容する形にして、`join`したものを渡してあげるでも良いかもしれませんね💡

2024-08-27 08:57 UTC, NByamane commented on src/app/country/[cca3]/page.tsx
> +            <CountryDetailItem title="Capital" value={country.capital} />
@NBmaeda 
ありがとうございます🙇‍♀️
string[]の型になる部分を.join(', ')で区切れるように指定し直しました👀
お手隙の際にご確認お願い致します🙏

2024-08-28 08:39 UTC, NBmaeda reviewed
問題ないと思います！
細かい点まで対応お疲れ様でした👏

2024-08-28 08:40 UTC, merged